# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PowerShell@2
  displayName: Veracode Software Composition Analysis OSS check
  inputs:
    targetType: 'inline'
    script: |
      $env:SRCCLR_API_TOKEN="$(SRCCLR_API_TOKEN)"
      Set-ExecutionPolicy AllSigned -Scope Process -Force
      $ProgressPreference = 'SilentlyContinue'
      iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
      srcclr scan

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'veracodeAzureJSKAPI'
    veracodeAppProfile: 'AzureVeraDemo'
    version: '$(build.buildNumber)'
    filepath: 'target/verademo.war'
    sandboxName: 'ADOVeraDemoJava'
    createSandBox: false
    createProfile: false
    failTheBuildIfVeracodeScanDidNotInitiate: false
    scanStatusCheckInterval: '60'
    importResults: true
    failBuildOnPolicyFail: false

- task: Veracode Flaw Importer@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'veracodeAzureJSKAPI'
    veracodeAppProfile: 'AzureVeraDemo'
    sandboxName: 'ADOVeraDemoJava'
    importType: 'All Unmitigated Flaws Violating Policy'
    workItemType: 'Bug'
    area: '$(system.teamProject)'
    flawImportLimit: '1000'
